apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: users
  description: List of user catalog-info yamls
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./mark-dutra-catalog-info.yaml
    - ./marvin-corea-catalog-info.yaml
