apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jaya-kumar7
spec:
  profile:
    displayName: Jaya K
    email: jaya.kumar@cvshealth.com
    picture: https://static.wikia.nocookie.net/villains/images/e/ee/Marvin_the_Martian.jpg
  memberOf: [devsecops]
